 **Question 1**  
 Apply a Function to Convert a Column to Uppercase
 Question: Create a function that takes a DataFrame and converts all strings in a specified
 column to uppercase using the apply method.


In [8]:
import pandas as pd
df=pd.DataFrame({"Name":["Alice","Bob","Charlie"],"Age":[25,30,35]})
def col_upper(df,col_name):
    df[col_name]=df[col_name].apply(str.upper)
    return df
col_upper(df,"Name")

Name  Age
0    ALICE   25
1      BOB   30
2  CHARLIE   35

**Question 2**  
 Calculate the Mean of Groups  
 Question: Write a function that groups a DataFrame by a specified column and calculates the
 mean of another numeric column using groupby

In [17]:
data={"Dept":["IT","IT","IT","HR","HR","HR","Finance","Finance"],"Expenses":[100,200,300,400,400,400,600,800]}
df=pd.DataFrame(data)
def func_groupby(df,col_group,col_mean):
    return df.groupby([col_group])[[col_mean]].mean()
func_groupby(df,"Dept","Expenses")

Expenses
Dept             
Finance     700.0
HR          400.0
IT          200.0

 **Question 3**  
 Create a function that adds a new column to the DataFrame, calculating the BMI (Body Mass
 Index) for each row using the apply method.
 Formula: BMI = weight (kg) / (height (m))²

In [110]:
df=pd.DataFrame({"Weight":[50,60,70],"Height":[1.60,1.70,1.80]})
def bmi(df):
    return df["Weight"]/(df["Height"]*df["Height"])
df["BMI"]=df.apply(lambda x:bmi(x),axis=1)
df

Weight  Height        BMI
0      50     1.6  19.531250
1      60     1.7  20.761246
2      70     1.8  21.604938

**Question 4**  
 Write a function that groups data by a column and counts the number of rows in each group
 using groupby.

In [39]:
data={"Dept":["IT","IT","IT","HR","HR","HR","Finance","Finance"],"Expenses":[100,200,300,400,400,400,600,800]}
df=pd.DataFrame(data)
def group_count(df,col_name):
    return df.groupby([col_name])[[col_name]].count()

group_count(df,"Dept")
            

Dept
Dept         
Finance     2
HR          3
IT          3

 **Question 5**  
 Question: Write a function to create a pivot table summarizing the total sales by region and
 product.

In [48]:
df=pd.DataFrame({"Region":["East","West","East","West"],"Product":["A","B","A","B"],"Sales":[100,200,150,300]})
pd.pivot_table(df,values=["Sales"],index=["Region"],columns=["Product"],aggfunc="sum")

Sales       
Product      A      B
Region               
East     250.0    NaN
West       NaN  500.0

**Question 6**  
 Write a function to normalize an array so that its values range between 0 and 1.

In [75]:
import numpy as np
array=np.arange(10,110,10)
print(array)
# norm=np.linalg.norm(array)
# print(norm)
# normalized_array=array/norm
# normalized_array
def normalize(array):
    norm_array=[]
    #formula for normalized array between 0 and 1 is (x-min_value)/(max_value-min_value)
    diff_arr=max(array)-min(array)
    for i in array:
        temp=(i-min(array))/diff_arr
        norm_array.append(temp)
    return np.array(norm_array)

norm_array=normalize(array)
print(norm_array)



[ 10  20  30  40  50  60  70  80  90 100]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


 **Question 7**  
 Write a function that computes the dot product of two 2D arrays.

In [83]:
array1=np.array([[1,2],[3,4]])
array2=np.array([[5,6],[7,8]])
def dot_product(array1,array2):
    dot_prod=np.dot(array1,array2)
    return dot_prod
dot_product(array1,array2)

array([[19, 22],
       [43, 50]])

**Question 8**  
 Write a function that replaces all negative values in a NumPy array with zero.

In [89]:
array=np.array([[-1,-2],[-3,4]])
def replace_neg(array):
    array[array<0]=0
    return array

replace_neg(array)

array([[0, 0],
       [0, 4]])

**Question 9**  
 Create a function that takes two 1D NumPy arrays and stacks them vertically

In [97]:
array1=np.array([1,2])
array2=np.array([3,4])
def stack_vertically(array1,array2):
    new_array=np.vstack((array1,array2))
    return new_array
stack_vertically(array1,array2)

array([[1, 2],
       [3, 4]])

 **Question 10**  
 Write a function that computes the length of strings in a column using the apply method.

In [108]:
df=pd.DataFrame({"Name":["Alice","Bob","Charlie"],"Age":[25,30,35]})
def col_length(df,col_name):
    df["Name_Length"]=df[col_name].apply(len)
    return df
col_length(df,"Name")

Name  Age  Name_Length
0    Alice   25            5
1      Bob   30            3
2  Charlie   35            7

In [109]:
df=pd.DataFrame({"Name":["Alice","Bob","Charlie"],"Age":[25,30,35]})
def col_len(string):
    x=len(string)
    return x
df["Name_Length"]=df["Name"].apply(lambda x:col_len(x))
df

Name  Age  Name_Length
0    Alice   25            5
1      Bob   30            3
2  Charlie   35            7

 **Question 11**  
 Write a function that groups a DataFrame by a specified column and calculates the maximum
 value of another column.


In [2]:
import pandas as pd
data={"Dept":["IT","IT","IT","HR","HR","HR","Finance","Finance"],"Expenses":[100,200,300,400,400,400,600,800]}
df2=pd.DataFrame(data)
def func_groupby2(df2,col_group,col_max):
    return df2.groupby([col_group])[[col_max]].max()
func_groupby2(df2,"Dept","Expenses")

Expenses
Dept             
Finance       800
HR            400
IT            300

**Question 12**  
 Write a function that filters rows where the value in a specified column exceeds a given
 threshold.

In [6]:
data={"Dept":["IT","IT","IT","HR","HR","HR","Finance","Finance"],"Expenses":[100,200,300,400,400,400,600,800]}
df3=pd.DataFrame(data)
def filter_col(df,col_name,criteria):
    return df[df[col_name]>criteria]
filter_col(df3,"Expenses",400)

Dept  Expenses
6  Finance       600
7  Finance       800

**Question 13**  
 Write a function that computes the mean and sum of a column for each group

In [19]:
data={"Dept":["IT","IT","IT","HR","HR","HR","Finance","Finance"],"Expenses":[100,200,300,400,400,400,600,800]}
df4=pd.DataFrame(data)
def mean_sum(df,group_by,agg_col):
    return df.groupby([group_by])[[agg_col]].agg(["mean","sum"])
mean_sum(df4,"Dept","Expenses")

Expenses      
            mean   sum
Dept                  
Finance    700.0  1400
HR         400.0  1200
IT         200.0   600

**Question 14**  
 Create a function that replaces missing values in a specified column with the column's mean.


In [16]:
df=pd.DataFrame({"Values":[1,2,None,4,None]})

def fill_na(df,col_name):
    df[col_name]=df[col_name].fillna(df[col_name].mean())
    return df
fill_na(df,"Values")


Values
0  1.000000
1  2.000000
2  2.333333
3  4.000000
4  2.333333

**Question 15**  
 Write a function that ranks values within groups using the rank method.

In [28]:
df=pd.DataFrame({"Group":["A","A","B","B"],"Value":[10,20,15,25]})
def rank_col(df,col_group,col_rank):
    df["Rank"]=df.groupby([col_group])[col_rank].rank()
    return df
rank_col(df,"Group","Value")

Group  Value  Rank
0     A     10   1.0
1     A     20   2.0
2     B     15   1.0
3     B     25   2.0

 **Question 16**  
 Write a function to compute the cumulative sum of a column within groups

In [53]:
df=pd.DataFrame({"Group":["X","X","Y","Y"],"Sales":[100,200,150,250]})
# def cumul_sum(df,group_col,sum_col):
#     df["Cumulative_Sum"]=df.groupby([group_col])[sum_col].transform("sum")
#     return df
# cumul_sum(df,"Group","Sales")
def cumul_sum(df,group_col,sum_col):
    df["Cumulative_Sum"]=df.groupby([group_col])[sum_col].cumsum()
    return df
cumul_sum(df,"Group","Sales")

Group  Sales  Cumulative_Sum
0     X    100             100
1     X    200             300
2     Y    150             150
3     Y    250             400

**Question 17**  
 Write a function that creates a new column by applying a custom function to an existing column

In [56]:
df=pd.DataFrame({"Items":["A","B","C","D"],"Quantity":[2,1,3,4],"Price":[100,200,300,400]})
def cust_func(df,col_name):
    df["Price_After_Tax"]=df[col_name]*1.16
    return df
cust_func(df,"Price")

Items  Quantity  Price  Price_After_Tax
0     A         2    100            116.0
1     B         1    200            232.0
2     C         3    300            348.0
3     D         4    400            464.0

**Question 18**  
 Write a function to extract the top N rows within each group based on a column.

In [15]:
df=pd.DataFrame({"Group":["A","A","B","B"],"Value":[10,20,15,25]})
def top_rows(df,group_col,value_col,top_n):
    new_df=df.groupby([group_col])[value_col].nlargest(top_n).reset_index(level=0)
    return new_df
top_rows(df,"Group","Value",1)

Group  Value
1     A     20
3     B     25

**Question 19**  
Write a function to compute the weighted average of a column within groups.

In [46]:
df=pd.DataFrame({"Category":["A","A","B","B"],"Value":[10,20,30,40],"Weight":[1,2,1,2]})

grouped=df.groupby(["Category"])
def func(grouped):
    d = grouped['Value']
    w = grouped['Weight']
    return (d * w).sum() / w.sum()

grouped.apply(func,include_groups=False)


Category
A    16.666667
B    36.666667
dtype: float64

In [48]:
df["Value"].median()

25.0