**Assignment 1--15th December 2024--Farhan Shabbir Butt**  
 **Question 1**  
 Write a function of name incr_val that takes 2 parameters
 1. Start
 2. End  
 append each element in the list and the element should be multiplied by 3 and addition of 1 to it
 list name should be bia_lst_two ,return this bia_lst_two

In [2]:
def incr_val(start,end):
    bia_lst_two=[]
    for i in range(start,end+1):
        bia_lst_two.append(i*3+1)
    return bia_lst_two
list_oper=incr_val(1,10)
print(list_oper)
    
    

[4, 7, 10, 13, 16, 19, 22, 25, 28, 31]


**Question 2**  
Write a function of name odd_func that takes 2 parameters  
 3. Start  
 4. End  
 append the element that is odd in the list bia_odd_lst and return this list

In [3]:
def odd_func(start,end):
    bia_odd_lst=[]
    for i in range(start,end+1):
        if i%2!=0:
            bia_odd_lst.append(i)
    return bia_odd_lst
odd_lst=odd_func(1,10)
print(odd_lst)

[1, 3, 5, 7, 9]


 **Question 3**  
 Write a function is_even,that takes a 1 parameter 
 1. No_val  
 Print if the number is even or not  

In [44]:
def is_even(no_val):
    if no_val%2==0:
        print("Number is even")
    else:
        print("Number is not even")
is_even(4)

Number is even


**Question 4**  
 Write a function is_odd,that takes a 1 parameter  
 2. No_val  
 Print if the number is odd or not  

In [45]:
def is_odd(no_val):
    if no_val%2!=0:
        print("Number is odd")
    else:
        print("Number is not odd")
is_odd(3)

Number is odd


**Question 5**  
 Write a function is_prime,that takes a 1 parameter  
 3. No_val  
 Print if the number is prime or not  

In [46]:
def is_prime(no_val):
    count_div=0
    if no_val<=1:
        print(f"{no_val} is not a prime number")
    else:
        for i in range(1,no_val+1):
            if no_val%i==0:
                count_div+=1                
        if count_div>2:
            print(f"{no_val} is not a prime number")
        else:
            print(f"{no_val} is a prime number")
is_prime(11)
        

11 is a prime number


 **Question 6**  
 Write a function fact,that takes a 1 parameter  
 4. No_val  
 And calculates the factorial of the number  

In [99]:
def fact(no_val):
    fact=1
    if no_val<=1:
        print(f"Factorial of {no_val} is 1.")
    else:
        for i in range(no_val,1,-2):
            fact=fact*(i*(i-1))
        print(f"Factorial of {no_val} is {fact}.")
fact(7)
        
    

Factorial of 7 is 5040.


**Question 7**  
 Write a function area_res , that takes length and width  
 1. Length  
2. width  
 And calculates the area of rectangle and return the area  

In [101]:
def area_res(length,width):
    area=length*width
    return area
area_res(3,4)

12

**Question 8**  
 Write a lambda function that sums two numbers

In [104]:
add=lambda a,b:a+b
add(5,5)

10

**Question 9**  
 Write a lambda function that multiplies two numbers

In [105]:
mul=lambda a,b:a*b
mul(5,5)

25

**Question 10**  
 Write a function,that takes a dictionary and a key,if that key exists in that dictionary return the
 value otherwise return "Key does not exist"

In [118]:
def dict_input(dict,key_input):
    for key in dict:
        if key==key_input:
            return dict[key]
    else:
        return print("Key does not exist")
dict_test={"name":"Farhan","nationality":"Pakistani","national_language":"Urdu"}
dict_input(dict_test,"age")

Key does not exist


**Question 11**  
 Write a function,that takes a dictionary and a key(age) ,if that key exists in that dictionary returns
 the value by multiplying it by 2 other wise return "Key does not exists"

In [122]:
def dict_input(dict,key_input):
    for key in dict:
        if key==key_input:
            return dict[key]*2
    else:
        return print("Key does not exist")
dict_test={"name":"Farhan","nationality":"Pakistani","national_language":"Urdu","age":40}
dict_input(dict_test,"age")

80

**Question 12**  
Write a function,that takes a dictionary ,and take all its values and appends in a list and return a
list

In [125]:

def dict_list(dict):
    list_output=[]
    for key in dict:
        list_output.append(dict[key])
    return list_output

dict_test2={"One":1,"Two":2,"Three":3,"Four":4,"Five":5}
dict_list(dict_test2)

[1, 2, 3, 4, 5]

**Question 13**  
 Write a function,that takes a dataframe and column , if that column exists return the entire
 column else return no such

In [151]:
import pandas as pd
def df_col(df,col_name):
    if col_name in df.columns:
        return df[[col_name]]
    else:
        return "Columnn does not exist"
dict_sample={"name":["Farhan","Alice","Bob","John"],"nationality":["Pakistani","British","British","American"],"national_language":["Urdu","English","English","English"]}
dict_df=pd.DataFrame.from_dict(dict_sample)
df_col(dict_df,"name")

name
0  Farhan
1   Alice
2     Bob
3    John

**Question 14**
 Write a function,that takes a dataframe and prints all the column name in that dataframe line by
 line
 
     

In [152]:
def col_print(df):
     for col in df.columns:
         print(col)
col_print(dict_df)

name
nationality
national_language


**Question 15**  
 Write a function,that takes a dataframe and a starting and ending location and return that
 dataframe with those specific rows

In [157]:
def return_data(df,start,end):
    return df[start:end+1]
return_data(dict_df,0,2)

name nationality national_language
0  Farhan   Pakistani              Urdu
1   Alice     British           English
2     Bob     British           English

 **Question 16**  
 Write a function,that takes a dataframe,and takes start and ending rows ,with the column
 location list and return the new dataframe

In [164]:
def return_coldata(df,start,end,column):
    new_df=df.iloc[start:end+1,column]
    return new_df
return_coldata(dict_df,0,2,[0,2])
    

name national_language
0  Farhan              Urdu
1   Alice           English
2     Bob           English

**Question 17**  
 Write a function, that takes a dataframe and a column and returns its unique values

In [167]:
def unique_val(df,column):
    list_uniq=df[column].unique()
    return list_uniq
unique_val(dict_df,"national_language")

array(['Urdu', 'English'], dtype=object)

**Question 18**  
Write a function that takes a dataframe and a col[Index] multiplies by 4 and saves it in the new
 column [index_new] this name should also be sent as a parameter

In [177]:
dict_df["index"]=[1,2,3,4]
def col_mult(df,col_index,col_new_index):
    df[col_new_index]=df[col_index]*4
    return df[[col_new_index]]
col_mult(dict_df,"index","new_index")
    

new_index
0          4
1          8
2         12
3         16

**Question 19**
 Write a Python program that checks if a given number is positive and prints a corresponding
 message.

In [180]:
def number_check(number):
    if number>0:
        print(f"{number} is a positive number")
number_check(5)

5 is a positive number


**Question 20**
 Create a Python program that determines whether a person is eligible to vote based on their
 age

In [184]:
def elig_vote(age):
    if age>=18:
        print("You are eligible to vote!")
    else:
        print("Sorry, you are under 18 and not eligible to vote.")
elig_vote(20)

You are eligible to vote!


**Question 21**
 Write a Python program that categorizes a student's grade based on their test score.

In [188]:
def stud_grade(score):
    if score>=90:
        grade="A+"
    elif score>=80:
        grade="A"
    elif score>=70:
        grade="B"
    elif score>=60:
        grade="C"
    elif score>=50:
        grade="D"
    elif score>=40:
        grade="E"
    else:
        grade="F"
    return grade
stud_grade(95)

'A+'

**Question 22**  
 Create a Python program that checks if a given number is even and positive, even and
 negative, odd and positive, or odd and negative.

In [194]:
def number_check(number):
    if number==0:
        print("Number is zero and is neutral")
    elif number%2==0:
        if number>0:
            print(f"{number} is even and positive.")
        else:
            print(f"{number} is even and negative.")
    elif number%2!=0:
        if number>0:
            print(f"{number} is odd and positive.")
        else:
            print(f"{number} is odd and negative.")
number_check(-2)

-2 is even and negative.


**Question 23**  
 **You are building a shopping cart application.** How would you use functions to calculate the total
 price of items in a cart with different quantities and prices?

In [216]:
def total_price(items):
    df_item=pd.DataFrame.from_dict(items)
    df_item["total_price"]=df_item.quantity*df_item.price
    total_sum=df_item["total_price"].sum()
    return total_sum

items={"item":["hanger","apples","oranges","banana","milk"],"quantity":[2,8,3,4,10],"price":[1,20,2,1,1]}
total=total_price(items)
print(total)

182


**Question 24**
 You are working on a data analysis project and need to apply a custom transformation to each
 element in a dataset. How can you use a function to apply this transformation efficiently

In [218]:
def transform(dataset):
    list_output=[]
    for value in dataset:
        list_output.append(value**2/2)
    return list_output
dataset=[1,2,3,4,5,6,7,8]
transform(dataset)

[0.5, 2.0, 4.5, 8.0, 12.5, 18.0, 24.5, 32.0]

 **Question 25**  
**You are developing a web application** and want to implement user authentication. How can you
 use functions to handle user login and validation?

In [273]:
def user_validate(all_user_info,username,password):
    if username in all_user_info.keys():
        if all_user_info[username]==password:
            print("Login Successful!")
        else:
            print("Check your password.")
    else:
        print("User not found.")
            
all_user_info={"user1":"password1","user2":"password2","user3":"password3","user4":"password4"}
user_validate(all_user_info,"user6","password3")

User not found.


**Question 26**  
 You are developing a game and need to track player statistics, such as health, score, and level.
 How can you use functions to update and display these statistics?

In [282]:
health=100
score=0
level="L1"
def player_stats_update(health_update,score_update,level_update):
    new_health=health_update
    new_score=score+score_update
    new_level=level_update
    print(f"Player Health is {new_health}.")
    print(f"Player score is {new_score}.")
    print(f"Player level is {new_level}.")
player_stats_update(80,200,"L2")

Player Health is 80.
Player score is 200.
Player level is L2.


**Question 27** 
 You are developing a scientific calculator application. How can you use functions to implement
 various mathematical operations like addition, subtraction, multiplication, and division?

In [284]:
def add(a,b):
    return a+b
def sub(a,b):
    return a-b
def mul(a,b):
    return a*b
def div(a,b):
    return a/b
print(add(2,2))
print(sub(4,2))
print(mul(2,8))
print(div(4,2))

4
2
16
2.0


 **Question 28**  
 **Write a Python function called authenticate_users**(users, input_username, input_password) that
 takes a list of user profiles, an input username, and an input password. The function should use
 a lambda function to filter the list of user profiles based on the provided username and
 password. If a matching user is found, return their profile; otherwise, return None

In [312]:
users={"user1":"password1","user2":"password2","user3":"password3","user4":"password4"}
def authenticate_users(users,input_user_name,input_password):
    result_user=lambda x:x in users.keys()
    result_pass=lambda y:y==users[input_user_name]
    if result_user(input_user_name):
        if result_pass(input_password):
            print("Login successful.")
        else:
            print("Incorrect password.")
    else:
        print("User not found.")
        
authenticate_users(users,"user2","password2")

Login successful.


**Question 29**  
 Write a Python function called sort_books_by_price_range(books, min_price, max_price) that
 takes a list of books, a minimum price, and a maximum price as input. The function should use a
 lambda function to filter and sort the books within the specified price range. It should return a
 sorted list of books that fall within the given price range.
 Each book is represented as a dictionary with 'title', 'author', and 'price' keys.

In [322]:
books=[{"title":"Book1","author":"writer1","price":20},{"title":"Book2","author":"writer2","price":30},
       {"title":"Book3","author":"writer3","price":40}]
def book_func(books,min_price,max_price):
    resulting_books=sorted(filter(lambda book:book["price"] >=min_price and book["price"]<=max_price,books),key=lambda book:book["price"])
    for book in resulting_books:
        print("Book title is ",book["title"],". Book Author is ",book["author"],". Book Price is ",book["price"])
book_func(books,24,45)

Book title is  Book2 . Book Author is  writer2 . Book Price is  30
Book title is  Book3 . Book Author is  writer3 . Book Price is  40


**Question 30**  
 You are provided with a dictionary containing employee names and their corresponding monthly
 salaries. Find and display the highest salary in the company. Calculate and print the average
 salary of all employees. Identify and display the names of employees who earn above a certain
 threshold (e.g., $5000). Sort and display the employee names in alphabetical order.

In [343]:
emp_records={"emp1":10000,"emp2":20000,"emp3":30000,"emp5":50000,"emp4":40000}
def max_salary(emp_records):
    max_sal=0
    for key in emp_records:
        if emp_records[key]>max_sal:
            max_sal=emp_records[key]
    return max_sal
def avg_salary(emp_records):
    avg_sal=sum(emp_records.values())/len(emp_records)
    return avg_sal
def high_salary(emp_records,high_sal_thresh):
    high_sal_emp=[]
    for key in emp_records:
        if emp_records[key]>high_sal_thresh:
            high_sal_emp.append(key)
    print("List of high salary employees:",high_sal_emp)
            
def sort_emp(emp_records):
    list_emp=list(emp_records.keys())
    print(sorted(list_emp))
    
print("Max Salary is ",max_salary(emp_records))
print("Average Salary is ",avg_salary(emp_records))
high_salary(emp_records,35000)
sort_emp(emp_records)

Max Salary is  50000
Average Salary is  30000.0
List of high salary employees: ['emp5', 'emp4']
['emp1', 'emp2', 'emp3', 'emp4', 'emp5']


**Question 31**  
  Extend the dictionary to include the age of each employee. Find and display the oldest
 employee in the company. Calculate and print the average age of all employees. Identify and
 display the names of employees who are younger than a certain age (e.g., 30). Sort and display
 the employee names based on age in ascending order.

In [364]:
emp_records2=[{"name":"emp1","salary":10000,"age":30},
            {"name":"emp2","salary":20000,"age":50},
             {"name":"emp3","salary":30000,"age":40},
              {"name":"emp4","salary":40000,"age":25}]

def old_age(emp_records2):
    oldest=0
    for emp in emp_records2:
        if emp["age"]>oldest:
            oldest=emp["age"]
    print("Oldest age is :",oldest)

def avg_age(emp_records2):
    age_list=[]
    for emp in emp_records2:
        age_list.append(emp["age"])
    average_age=sum(age_list)/len(age_list)
    print(f"Average age is :{average_age}.")

def young_emp(emp_records2,young_age):
    young_emp=[]
    for emp in emp_records2:
        if emp["age"]<young_age:
            young_emp.append(emp["name"])
    print("List of young employees: ",young_emp)

def sort_age(emp_records2):
    sorted_age=sorted(emp_records2,key=lambda emp:emp["age"])
    print("Employees sorted by age:")
    for emp in sorted_age:
        print(emp["name"])

old_age(emp_records2)
avg_age(emp_records2)
young_emp(emp_records2,30)        
sort_age(emp_records2)

Oldest age is : 50
Average age is :36.25.
List of young employees:  ['emp4']
Employees sorted by age:
emp4
emp1
emp3
emp2


**Question 32**  
 Add a new key to the dictionary to represent the performance rating of each employee (on a
 scale of 1 to 10). Identify and display the names of employees with the highest performance
 rating. Calculate and print the average performance rating of all employees. Identify and display
 the names of employees with a rating above a certain threshold (e.g., 8). Sort and display the
 employee names based on their performance rating in descending order.

In [388]:
emp_records3=[{"name":"emp1","salary":10000,"age":30,"rating":8},
            {"name":"emp2","salary":20000,"age":50,"rating":7},
             {"name":"emp3","salary":30000,"age":40,"rating":9},
              {"name":"emp4","salary":40000,"age":25,"rating":6}]

def highest_rating(emp_records3):
    sorted_result=sorted(emp_records3,key=lambda emp:emp["rating"],reverse=True)
    print("Highest rated employee is:")
    print(sorted_result[0]["name"])

def avg_rating(emp_records3):
    ratings=[]
    for emp in emp_records3:
        ratings.append(emp["rating"])
    average_rating=sum(ratings)/len(ratings)
    print("Average rating of employees is :",average_rating)
        
def high_rating(emp_records3,rating_criteria):
    rated_emp=[]
    for emp in emp_records3:
        if emp["rating"]>rating_criteria:
            rated_emp.append(emp["name"])
    print("High rated employees are:",rated_emp)
            
def sort_rating(emp_records3):
    sorted_emp=sorted(emp_records3,key=lambda emp:emp["rating"],reverse=True)
    print("Employee names sorted in terms of their rating in descending order:")
    for sorted_employee in sorted_emp:
        print(sorted_employee["name"])
    
highest_rating(emp_records3)
avg_rating(emp_records3)
high_rating(emp_records3,8)
sort_rating(emp_records3)
    
    
        

Highest rated employee is:
emp3
Average rating of employees is : 7.5
High rated employees are: ['emp3']
Employee names sorted in terms of their rating in descending order:
emp3
emp1
emp2
emp4


**Question 33**  
 Assume that each employee is eligible for a bonus based on their performance. Calculate and
 display the bonus amount for each employee (bonus = 10% of their salary). Identify and display
 the names of employees who are eligible for a bonus (performance rating above 5). Sort and
 display the employee names based on the bonus amount in descending order.

In [403]:
emp_records4=[{"name":"emp1","salary":10000,"age":30,"rating":8},
            {"name":"emp2","salary":20000,"age":50,"rating":7},
             {"name":"emp3","salary":30000,"age":40,"rating":9},
              {"name":"emp4","salary":40000,"age":25,"rating":4}]
def calc_bonus(emp_records4):
    for emp in emp_records4:
        print("Employee ",emp["name"]," bonus amount is ",{emp["salary"]*0.10},".")

def bonus_eligible(emp_records4):
    print("Employees eligible for bonus are:")
    for emp in emp_records4:
        if emp["rating"]>5:
            print("Employee ",emp["name"]," is eligible for bonus.")

def sort_bonus(emp_records4):
    for emp in emp_records4:
        emp["bonus"]=emp["salary"]*0.10
    sorted_by_bonus=sorted(emp_records4,key=lambda emp:emp["bonus"],reverse=True)
    print("List of employees sorted by their bonus amount in descending order:")
    for emp in sorted_by_bonus:
        print(emp["name"])
    

calc_bonus(emp_records4)               
bonus_eligible(emp_records4)
sort_bonus(emp_records4)
    

Employee  emp1  bonus amount is  {1000.0} .
Employee  emp2  bonus amount is  {2000.0} .
Employee  emp3  bonus amount is  {3000.0} .
Employee  emp4  bonus amount is  {4000.0} .
Employees eligible for bonus are:
Employee  emp1  is eligible for bonus.
Employee  emp2  is eligible for bonus.
Employee  emp3  is eligible for bonus.
List of employees sorted by their bonus amount in descending order:
emp4
emp3
emp2
emp1


 **Question 34**  
 Write a function create_dataframe () that creates and returns a DataFrame with the following
 data:  
 Name   Age   City  
 Alice  25   New York  
 Bob    30   San Francisco  
 Charlie 35 Chicago  

In [417]:
def create_dataframe():
    data={"Name":["Alice","Bob","Charlie"],"Age":[25,30,35],"City":["New York","San Francisco","Chicago"]}
    df=pd.DataFrame(data)
    return df
df=create_dataframe()
print(df)
    

      Name  Age           City
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   35        Chicago


 **Question 35**  
 Write a function filter_age(df, age_threshold) that takes a DataFrame and an age threshold as
 arguments.
 The function should return all rows where the Age is greater than the given threshold.


In [420]:
def filter_age(df,age_threshold):
    filtered_df=df[df.Age>age_threshold]
    return filtered_df
filter_age(df,25)

Name  Age           City
1      Bob   30  San Francisco
2  Charlie   35        Chicago

**Question 36**  
 Write a function fill_missing_ages(df) that takes a DataFrame and replaces missing values in
 the Age column with the average age.

In [456]:
data2={"Name":["Alice","Bob","Charlie","Akram"],"Age":[25,30,35,""],"City":["New York","San Francisco","Chicago","Lahore"]}
df_new=pd.DataFrame(data2)

def fill_missing_ages(df):
    df["Age"]=pd.to_numeric(df["Age"],errors="coerce").astype("Int64")
    df["Age"]=df["Age"].fillna(df["Age"].mean())
    print(df)
df4=fill_missing_ages(df_new)


      Name  Age           City
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   35        Chicago
3    Akram   30         Lahore


**Question 37**   
 Write a function group_by_city(df) that groups the DataFrame by the City column and returns
 the average age for each city.

In [461]:
data2={"Name":["Alice","Bob","Charlie","Akram"],"Age":[25,30,35,30],"City":["New York","San Francisco","Chicago","New York"]}
df_3=pd.DataFrame(data2)

def group_by_city(df):
    df_output=df.groupby("City")["Age"].mean()
    return df_output

group_by_city(df_3)
    
    
    

City
Chicago          35.0
New York         27.5
San Francisco    30.0
Name: Age, dtype: float64

 **Question 38**  
 Write a function add_income_column(df, income_list) that takes a DataFrame and a list of
 incomes as arguments.
 The function should add a new column named Income to the DataFrame using the provided list.

In [463]:
def add_income_column(df,income_list):
    df["Income"]=income_list
    return df


income_list=[100,200,300,400]
add_income_column(df_3,income_list)

Name  Age           City  Income
0    Alice   25       New York     100
1      Bob   30  San Francisco     200
2  Charlie   35        Chicago     300
3    Akram   30       New York     400

**Question 39**  
 Write a function create_array() that creates and returns a 2D NumPy array with the following
 data:  
 [[1, 2, 3],  
 [4, 5, 6],  
 [7, 8, 9]]

In [471]:
import numpy as np
def create_array():
    list_input=[[1,2,3],[4,5,6],[7,8,9]]
    array_output=np.array(list_input)
    return array_output

array_new=create_array()
print(array_new)
    

[[1 2 3]
 [4 5 6]
 [7 8 9]]


 **Question 40**  
 Write a function square_elements(arr) that takes a NumPy array as input and returns a new
 array with each element squared.

In [472]:
def square_elements(arr):
    sq_array=arr**2
    return sq_array

square_elements(array_new)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

 **Question 41**  
 Write a function find_max(arr) that takes a NumPy array as input and returns the maximum
 value in the array.

In [494]:
def find_max(arr):
    max_val=arr.max()
    return max_val

find_max(array_new)


np.int64(9)

 **Question 42**  
 Write a function matrix_multiply(arr1, arr2) that takes two 2D NumPy arrays as input and returns
 their matrix product.

In [490]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])

def matrix_multiply(arr1,arr2):
    matrix_product=np.matmul(arr1,arr2)
    return matrix_product

matrix_multiply(arr1,arr2)

array([[30, 36, 42],
       [66, 81, 96]])

 **Question 43**  
 Write a function array_mean(arr) that takes a NumPy array as input and returns the mean of all
 elements in the array

In [493]:
print(array_new)
def array_mean(arr):
    return arr.mean()

array_mean(array_new)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


np.float64(5.0)